### ISSUE TITLE
帮助

### ISSUE THREAD

**Issue by DexSinis** [xiaokekeT/ddx#1]
能不能说明一下怎么启动你的项目啊，接触这个不久，能写详细点么
node hot.js 

ERROR in HtmlWebpackPlugin: Unable to read HTML template "app/src/index.template.html"
webpack: bundle is now VALID.

**Comment by xesrevinu** [comment]
启动就四条命令，package.json里面scripts字段可以看到。这段时间比较忙，很多改动没commit，过几天时间够了，完整的发上来。不过现在这样应该是能跑起来的。

**Comment by xiaokekeT** [comment]
启动就四条命令，package.json里面scripts字段可以看到。这段时间比较忙，很多改动没commit，过几天时间够了，完整的发上来。不过现在这样应该是能跑起来的。

**Comment by DexSinis** [comment]
上传了回复我一下，对这项目很感兴趣

**Comment by xesrevinu** [comment]
周六整理下上传
https://github.com/xiaokekeT/ddx/issues/2

**Comment by xesrevinu** [comment]
@DexSinis 提交了，try一try
