### ISSUE TITLE
npm run client-watch

### ISSUE THREAD

**Issue by zanjs** [xiaokekeT/ddx#5]
[1047] ./~/redux-devtools/lib/react/DebugPanel.js 3.44 kB {0}

ERROR in ./app/src/components/customPosts/music/index.js

/Users/julaud/www/react/reactjs/redux/reduxBlog/app/src/components/customPosts/music/index.js
  107:6  error  Missing space before keyword "else"  space-before-keywords

✖ 1 problem (1 error, 0 warnings)

ERROR in ./app/src/components/navbar/index.js

/Users/julaud/www/react/reactjs/redux/reduxBlog/app/src/components/navbar/index.js
  161:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  165:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  169:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  170:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs

✖ 4 problems (4 errors, 0 warnings)

**Comment by xesrevinu** [comment]
少了个空格，和混用了制表符，你找到出错行数改掉就行了
